### ISSUE TITLE
%Z formatting

### ISSUE THREAD

**Issue by washu** [rubysl/rubysl-date#12]
Currenlty only shows the OFFSET instead of the zone name

**Comment by brixen** [comment]
Could you provide code, please.

**Comment by washu** [comment]
Nevermind, closing the ticket, it seems %Z only works if the object is a Time object. when created as a DateTime both mri and rbx return same result. either case it really is a bug as the %Z option should relfect properly insted of as the raw offset value. However since this is a bug in MRI and RBX im closing it here and going to open a ticket against MRI
